/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 sushi.glb
Author: Pedro Lima (https://sketchfab.com/Panza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sushibar-scene-baked-ea82f6a9bb844299905cd99e57dc3bb5
Title: Sushibar Scene Baked
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/sushi.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.floorandwalls_uv_floor_0.geometry} material={materials.floor} position={[0, 2.46, 0]} scale={[13.61, 4.91, 11.97]} />
      <mesh geometry={nodes.MovelMadeira_uv_aiStandardSurface16_0.geometry} material={materials.aiStandardSurface16} position={[-2.59, 2.56, -0.5]} scale={[0.13, 5.15, 2.88]} />
      <mesh geometry={nodes.Mesadosushi_uv_aiStandardSurface14_0.geometry} material={materials.aiStandardSurface14} position={[-2.35, 1.22, -0.5]} scale={[0.15, 2.5, 2.84]} />
      <mesh geometry={nodes.Door_uv_aiStandardSurface10_0.geometry} material={materials.aiStandardSurface10} position={[-6.74, 2.73, -2.9]} scale={[0.27, 5.64, 2.41]} />
      <mesh geometry={nodes.mesatrabaio_uv_aiStandardSurface11_0.geometry} material={materials.aiStandardSurface11} position={[2.16, 2.42, -5.38]} scale={[9.35, 0.14, 1.26]} />
      <mesh geometry={nodes.decoraquadro_uv_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
      {/* <mesh geometry={nodes.maquinarefri_uv_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} /> */}
      <mesh geometry={nodes.pCylinder9_aiStandardSurface8_0.geometry} material={materials.aiStandardSurface8} />
      <mesh geometry={nodes.bancadasushi_uv2_aiStandardSurface12_0.geometry} material={materials.aiStandardSurface12} />
      <mesh geometry={nodes.lamp_uv4_aiStandardSurface15_0.geometry} material={materials.aiStandardSurface15} />
      <mesh geometry={nodes.sushitable_aiStandardSurface13_0.geometry} material={materials.aiStandardSurface13} position={[-2.91, 0.88, -0.99]} rotation={[0, 0.03, 0]} scale={0.66} />
      <mesh geometry={nodes.sushiplatedesk_aiStandardSurface5_0.geometry} material={materials.aiStandardSurface5} position={[-2.06, 0.67, 0.38]} scale={0.66} />
      <mesh geometry={nodes.sushiplatedesk1_lambert4_0.geometry} material={materials.lambert4} position={[4.3, 0.67, 0.38]} scale={0.66} />
      <mesh geometry={nodes.pCylinder10_lambert2_0.geometry} material={materials.lambert2} position={[3.05, 0, -0.06]} rotation={[0, 0.11, 0]} />
      <mesh geometry={nodes.pCylinder11_lambert3_0.geometry} material={materials.lambert3} position={[6.28, 0, -0.12]} />
      <mesh geometry={nodes.sushiplatedesk2_lambert5_0.geometry} material={materials.lambert5} position={[1.16, 0.67, 0.38]} scale={0.66} />
      <mesh geometry={nodes.bancadasushi_uv3_lambert7_0.geometry} material={materials.lambert7} position={[2.1, 0, 0.01]} rotation={[0, -0.05, 0]} />
      <mesh geometry={nodes.lamp_uv5_lambert9_0.geometry} material={materials.lambert9} position={[3.51, 0, 0]} />
      <mesh geometry={nodes.lamp_uv6_lambert8_0.geometry} material={materials.lambert8} position={[6.85, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/sushi.glb')
