/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/lightroom2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-3.24, -3.62, -10.78]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-345.69, -902.96, 291.98]} rotation={[-Math.PI / 2, 1.12, 0]}>
              <mesh geometry={nodes.basement_274_basement_274Mat_0.geometry} material={materials.basement_274Mat} />
            </group>
            <group position={[-368.26, -894.76, 623.3]} rotation={[-Math.PI / 2, 1.12, 0]}>
              <mesh geometry={nodes.ceiling_377_ceiling_377Mat_0.geometry} material={materials.ceiling_377Mat} />
            </group>
            <group position={[-142.17, -865.9, 301.11]} rotation={[-Math.PI / 2, 1.12, 0]}>
              <mesh geometry={nodes.dining_arrangement_492_dining_arrangement_492Mat_0.geometry} material={materials.dining_arrangement_492Mat} />
            </group>
            <group position={[-290.51, -929.32, 603]} rotation={[-Math.PI / 2, 1.12, 0]}>
              <mesh geometry={nodes.flat_areas_372_flat_areas_372Mat_0.geometry} material={materials.flat_areas_372Mat} />
            </group>
            <group position={[-345.24, -902.74, 220]} rotation={[-Math.PI / 2, 1.12, 0]}>
              <mesh geometry={nodes.floor_inside_376_floor_inside_376Mat_0.geometry} material={materials.floor_inside_376Mat} />
            </group>
            <group position={[-309.8, -908.03, 520]} rotation={[-Math.PI / 2, 1.12, 0]}>
              <mesh geometry={nodes.glass_794_glass_794Mat_0.geometry} material={materials.glass_794Mat} />
            </group>
            <group position={[-345.24, -902.74, 520]} rotation={[-Math.PI / 2, 1.12, 0]}>
              <mesh geometry={nodes.inner_walls_798_inner_walls_798Mat_0.geometry} material={materials.inner_walls_798Mat} />
            </group>
            <group position={[-2787.52, -1528.52, 10.02]} rotation={[-Math.PI / 2, 1.12, 0]}>
              <mesh geometry={nodes.Island_1_807_Island_1_807Mat_0.geometry} material={materials.Island_1_807Mat} />
            </group>
            <group position={[-362.64, -896.79, 520]} rotation={[-Math.PI / 2, 1.12, 0]}>
              <mesh geometry={nodes.outer_walls_1_outer_walls_1Mat_0.geometry} material={materials.outer_walls_1Mat} />
            </group>
            <group position={[-1968.58, -1301.18, 396.82]} rotation={[-Math.PI / 2, 1.12, 0]}>
              <group position={[9.92, 292.52, 29.75]} rotation={[Math.PI / 2, 0, -1.01]}>
                <mesh geometry={nodes['2d_silhouette_man_standing_813_2d_silhouette_man_standing_813Ma'].geometry} material={materials['2d_silhouette_man_standing_813Mat']} />
              </group>
              <group position={[1301.4, 194.95, 2422.5]} rotation={[-Math.PI / 2, 0, 1.01]} scale={-1}>
                <group position={[27.36, 0, 0]}>
                  <mesh geometry={nodes.Man_2_812_Man_2_812Mat_0.geometry} material={materials.Man_2_812Mat} />
                </group>
                <group position={[-24.45, 0, 0]}>
                  <mesh geometry={nodes.Man_811_Man_811Mat_0.geometry} material={materials.Man_811Mat} />
                </group>
              </group>
              <group position={[962.14, 209.59, 1017.13]} rotation={[-Math.PI / 2, 0, 1.01]} scale={-1}>
                <mesh geometry={nodes['2d_silhouette,_woman_walking_with_short_hair_814_2d_silhouette,'].geometry} material={materials['2d_silhouette_woman_walking_with_short_hair_814Mat']} />
              </group>
            </group>
            <group position={[-59.88, -1134.14, 379.95]} rotation={[-Math.PI / 2, 1.12, 0]}>
              <mesh geometry={nodes.seating_arrangement_578_seating_arrangement_578Mat_0.geometry} material={materials.seating_arrangement_578Mat} />
            </group>
            <group position={[-342.2, -931.32, 595.8]} rotation={[-Math.PI / 2, 1.12, 0]}>
              <mesh geometry={nodes.various_decoration_inside_616_various_decoration_inside_616Mat_.geometry} material={materials.various_decoration_inside_616Mat} />
            </group>
            <group position={[-318.75, -889.76, 595.8]} rotation={[-Math.PI / 2, 1.12, 0]}>
              <mesh geometry={nodes.window_frames_3_684_window_frames_3_684Mat_0.geometry} material={materials.window_frames_3_684Mat} />
            </group>
          </group>
        </group>
      </group>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} />
    </group>
  )
}

useGLTF.preload('/models/lightroom2.glb')
